name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create File
      run: |
        touch test-file.txt
        echo "My test file" > test-file.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: test-file-${{ github.sha }}
        path: test-file.txt
